### ISSUE TITLE
Is context important in any use-case?

### ISSUE THREAD

**Issue by Etheryte** [showpad/angular-q-spread#13]
Currently, context is discarded in spread:

```
function spread (data) {
    return resolve.apply(void 0, data);
}
```

Do any use-cases exist where keeping the previous context would benefit the end-user?

**Comment by klaascuvelier** [comment]
I'm not sure, but I don't think so.

I am not really sure (anymore) why I decided to do a `call`, instead of just invoking the function like 
````
function spread (data) {
    return resolve(data);
}
````
as that is what happens in $q: https://github.com/angular/angular.js/blob/master/src/ng/q.js#L317

I assume we can just change this, all though, I don't think this will have much impact.
The callback functions in `then` (and `spread` for that matter) probably won't use `this` but rather `_this`, `self` (or any other reference to the parent `this`) as the context would be different anyway.
I also assume this would not impact arrow function callbacks either.

But interesting to bring it up.

**Comment by Etheryte** [comment]
The `.apply()` is the whole point of this small module, isn't it? It makes the array of parameters available as separate parameters.

**Comment by klaascuvelier** [comment]
Oh god yes! :D
